//! The router-mode model preset file.
//!
//! Jade runs **one** `llama-server`, in router mode, serving two models:
//!
//! | preset | model | serves |
//! |---|---|---|
//! | [`FIM_MODEL`] | a fill-in-the-middle GGUF | ghost text, over `/infill` |
//! | [`CHAT_MODEL`] | an instruct GGUF | Explain / Visualize, over `/v1/chat/completions` |
//!
//! Two models are needed because one cannot do both jobs. Asked to chat, a base
//! or FIM model produces control-token noise rather than prose: llama-server
//! wraps the prompt in a generic ChatML template, the model has no instruction
//! tuning, and its EOS (`<|endoftext|>`) does not match the template's turn
//! terminator (`<|im_end|>`), so it emits `<|im_end|><|im_start|>assistant` on a
//! loop until the token budget runs out.
//!
//! One *server* is enough because llama.cpp's router loads a preset on demand
//! and holds at most `--models-max` at once. An idle Jade therefore holds no
//! weights, and asking for an explanation costs one load rather than a second
//! supervised process.
//!
//! The file is an INI whose section name is the id a client selects with the
//! request's `model` field, and whose keys are `llama-server`'s long options
//! with the leading dashes removed (`common/preset.cpp`, `load_from_ini`).

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

use crate::{AiModelId, ModelSource};

/// The `model` id for fill-in-the-middle requests.
pub const FIM_MODEL: &str = "jade-fim";
/// The `model` id for chat requests.
pub const CHAT_MODEL: &str = "jade-chat";

/// How many presets the router may hold loaded at once. Two: ours.
pub const MODELS_MAX: &str = "2";

/// Instruct tiers for the chat preset.
///
/// The default tier is the newest Qwen instruct generation: verified on this
/// machine (2026-08-18, llama-server 9960) to load via `-hf`, follow a JSON
/// schema under grammar constraint, and write clean prose with no thinking
/// tags — the 2507 Instruct line has no thinking mode to leak. The other two
/// tiers stay on Qwen2.5-Coder for now: the non-2507 Qwen3 hybrids default to
/// thinking mode, whose `<think>` blocks would land in the card as prose.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum ChatTier {
    /// Qwen2.5-Coder 1.5B Instruct, about 1.6GB. It names what a fragment
    /// does, but rarely says how, and it ignores a length target.
    Fast,
    /// Qwen3 4B Instruct 2507, about 4.3GB. The default: the newest small
    /// instruct tier, and the smallest that follows the prompt's structure
    /// and length instead of answering in one flat sentence.
    #[default]
    Balanced,
    /// Qwen2.5-Coder 7B Instruct, about 8.1GB.
    Best,
}

impl ChatTier {
    /// The `-hf`-style reference. A `:QUANT` tag after the repo selects the
    /// file, exactly as on the `llama-server -hf` command line.
    pub fn repo(self) -> &'static str {
        match self {
            ChatTier::Fast => "ggml-org/Qwen2.5-Coder-1.5B-Instruct-Q8_0-GGUF",
            ChatTier::Balanced => "unsloth/Qwen3-4B-Instruct-2507-GGUF:Q8_0",
            ChatTier::Best => "ggml-org/Qwen2.5-Coder-7B-Instruct-Q8_0-GGUF",
        }
    }

    pub fn label(self) -> &'static str {
        match self {
            ChatTier::Fast => "Qwen2.5-Coder 1.5B Instruct",
            ChatTier::Balanced => "Qwen3 4B Instruct 2507",
            ChatTier::Best => "Qwen2.5-Coder 7B Instruct",
        }
    }

    /// Rough download and resident size, for the "this will fetch N" message.
    pub fn approx_gb(self) -> f32 {
        match self {
            ChatTier::Fast => 1.6,
            ChatTier::Balanced => 4.3,
            ChatTier::Best => 8.1,
        }
    }
}

/// Where the generated preset file lives.
pub fn default_path() -> PathBuf {
    let home = std::env::var_os("HOME").map(PathBuf::from).unwrap_or_default();
    home.join(".config/jade/models.ini")
}

/// Render the preset file.
///
/// Pure, so the exact bytes handed to `llama-server` are testable — a silently
/// malformed section makes the router refuse to start with only a parse error
/// naming the file.
pub fn render(fim: AiModelId, chat: ChatTier) -> String {
    let mut out = String::new();
    out.push_str(
        "; Generated by Jade. Edits are overwritten when the model tier changes.\n\
         ; Section name = the `model` id a request selects; keys are llama-server\n\
         ; long options without their leading dashes.\n\n",
    );

    let _ = writeln!(out, "[{FIM_MODEL}]");
    match fim.source() {
        ModelSource::Hf(repo) => {
            let _ = writeln!(out, "hf-repo = {repo}");
        }
        ModelSource::Local(path) => {
            let _ = writeln!(out, "model = {}", path.display());
        }
    }
    // Full GPU offload (Metal), the model's own context window, and the
    // KV-prefix reuse the completion path depends on. The batch size is a
    // quality knob for FIM, not only throughput: llama-server derives how much
    // prefix `/infill` keeps from it (`n_prefix_take = 3*(n_batch/4)`).
    let batch = fim.batch();
    let _ = writeln!(out, "n-gpu-layers = 99");
    let _ = writeln!(out, "batch-size = {batch}");
    let _ = writeln!(out, "ubatch-size = {batch}");
    let _ = writeln!(out, "ctx-size = 0");
    let _ = writeln!(out, "cache-reuse = 256");

    let _ = writeln!(out, "\n[{CHAT_MODEL}]");
    let _ = writeln!(out, "hf-repo = {}", chat.repo());
    let _ = writeln!(out, "n-gpu-layers = 99");
    // A FIXED window, never 0 ("the model's own"): Qwen3's native window is
    // 262144 tokens, and a KV cache that size aborts llama_decode on Metal
    // ("Compute error", verified on the reference machine). 32768 is the
    // window the Explain budgets were sized against, and every tier here
    // serves at least that much.
    let _ = writeln!(out, "ctx-size = 32768");
    // One slot, so a request gets the model's WHOLE context window.
    //
    // llama-server divides `ctx-size` between `parallel` slots, and it defaults
    // to 4 — which quietly turns Qwen2.5-Coder's 32768 tokens into 8192 per
    // request. Explain is single-flight by construction, so the other three
    // slots buy nothing and cost three quarters of the context.
    let _ = writeln!(out, "parallel = 1");
    // Explicitly on: chat must use the model's OWN chat template, not
    // llama.cpp's generic ChatML fallback. This is the difference between
    // prose and control-token noise.
    let _ = writeln!(out, "jinja = true");
    out
}

/// Write the preset file, creating its directory.
pub fn write(path: &Path, fim: AiModelId, chat: ChatTier) -> std::io::Result<()> {
    if let Some(dir) = path.parent() {
        std::fs::create_dir_all(dir)?;
    }
    std::fs::write(path, render(fim, chat))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn parse(ini: &str) -> Vec<(String, Vec<(String, String)>)> {
        let mut out: Vec<(String, Vec<(String, String)>)> = Vec::new();
        for line in ini.lines() {
            let line = line.trim();
            if line.is_empty() || line.starts_with(';') {
                continue;
            }
            if let Some(name) = line.strip_prefix('[').and_then(|l| l.strip_suffix(']')) {
                out.push((name.to_string(), Vec::new()));
            } else if let Some((k, v)) = line.split_once('=') {
                out.last_mut()
                    .expect("a key before any section")
                    .1
                    .push((k.trim().to_string(), v.trim().to_string()));
            }
        }
        out
    }

    #[test]
    fn both_presets_are_emitted_with_the_ids_requests_select() {
        let ini = render(AiModelId::Fast, ChatTier::Fast);
        let secs = parse(&ini);
        let names: Vec<&str> = secs.iter().map(|(n, _)| n.as_str()).collect();
        assert_eq!(names, vec![FIM_MODEL, CHAT_MODEL]);
    }

    /// The chat preset must serve an INSTRUCT model and turn jinja on. Either
    /// one wrong reproduces the control-token loop this file exists to avoid.
    #[test]
    fn the_chat_preset_is_instruct_and_uses_the_models_own_template() {
        for tier in [ChatTier::Fast, ChatTier::Balanced, ChatTier::Best] {
            let ini = render(AiModelId::Fast, tier);
            let chat = parse(&ini)
                .into_iter()
                .find(|(n, _)| n == CHAT_MODEL)
                .unwrap()
                .1;
            let repo = chat.iter().find(|(k, _)| k == "hf-repo").unwrap();
            assert!(repo.1.contains("-Instruct-"), "not an instruct repo: {}", repo.1);
            assert_eq!(
                chat.iter().find(|(k, _)| k == "jinja").map(|(_, v)| v.as_str()),
                Some("true"),
                "jinja must be on or llama.cpp uses a generic ChatML template"
            );
        }
    }

    /// A local GGUF uses `model =`, a HuggingFace tier uses `hf-repo =`. Using
    /// the wrong key makes the router try to download a filesystem path.
    #[test]
    fn a_local_fim_model_is_pointed_at_by_path() {
        let ini = render(AiModelId::Sprite, ChatTier::Fast);
        let fim = parse(&ini).into_iter().next().unwrap().1;
        assert!(fim.iter().any(|(k, _)| k == "model"));
        assert!(!fim.iter().any(|(k, _)| k == "hf-repo"));

        let ini = render(AiModelId::Fast, ChatTier::Fast);
        let fim = parse(&ini).into_iter().next().unwrap().1;
        assert!(fim.iter().any(|(k, _)| k == "hf-repo"));
        assert!(!fim.iter().any(|(k, _)| k == "model"));
    }

    /// `/infill` derives how much prefix it keeps from the batch size, so the
    /// per-tier value has to survive into the preset.
    #[test]
    fn the_fim_batch_size_is_carried_through() {
        let ini = render(AiModelId::Sprite, ChatTier::Fast);
        let fim = parse(&ini).into_iter().next().unwrap().1;
        let batch = AiModelId::Sprite.batch().to_string();
        assert_eq!(
            fim.iter().find(|(k, _)| k == "batch-size").map(|(_, v)| v.clone()),
            Some(batch.clone())
        );
        assert_eq!(
            fim.iter().find(|(k, _)| k == "ubatch-size").map(|(_, v)| v.clone()),
            Some(batch)
        );
    }

    /// Keys are long options with the dashes stripped; a stray `--` makes the
    /// router reject the whole file.
    #[test]
    fn no_key_carries_leading_dashes() {
        let ini = render(AiModelId::Fast, ChatTier::Fast);
        for (_, keys) in parse(&ini) {
            for (k, _) in keys {
                assert!(!k.starts_with('-'), "key {k:?} has leading dashes");
            }
        }
    }

    /// The chat window must be FIXED, never 0 ("the model's own"): Qwen3's
    /// native 262k window makes a KV cache that aborts llama_decode on Metal.
    #[test]
    fn the_chat_preset_pins_a_fixed_context_window() {
        let ini = render(AiModelId::Fast, ChatTier::Balanced);
        let chat = parse(&ini)
            .into_iter()
            .find(|(n, _)| n == CHAT_MODEL)
            .unwrap()
            .1;
        assert_eq!(
            chat.iter().find(|(k, _)| k == "ctx-size").map(|(_, v)| v.as_str()),
            Some("32768"),
            "ctx-size 0 with a 262k-window model is a Metal OOM"
        );
    }

    /// llama-server splits the context window between parallel slots, so
    /// leaving the default of 4 would give a request a quarter of the window.
    #[test]
    fn the_chat_preset_asks_for_a_single_slot() {
        let ini = render(AiModelId::Fast, ChatTier::Balanced);
        let chat = parse(&ini)
            .into_iter()
            .find(|(n, _)| n == CHAT_MODEL)
            .unwrap()
            .1;
        assert_eq!(
            chat.iter().find(|(k, _)| k == "parallel").map(|(_, v)| v.as_str()),
            Some("1")
        );
    }

    /// The default has to be the tier that actually follows the prompt. The
    /// 1.5B answers in one flat sentence however the prompt is written, and
    /// the newest instruct generation is preferred over Qwen2.5.
    #[test]
    fn the_default_chat_tier_is_the_latest_qwen() {
        assert_eq!(ChatTier::default(), ChatTier::Balanced);
        assert!(ChatTier::default().repo().contains("Qwen3-4B-Instruct-2507"));
        // Never a Thinking variant: `<think>` blocks would land in the card.
        assert!(!ChatTier::default().repo().contains("Thinking"));
    }

    #[test]
    fn tiers_are_ordered_by_size() {
        assert!(ChatTier::Fast.approx_gb() < ChatTier::Balanced.approx_gb());
        assert!(ChatTier::Balanced.approx_gb() < ChatTier::Best.approx_gb());
    }
}
