//! Generator for `jade_hw_top.v`, the fixed-port board wrapper.
//!
//! The C++ harness never changes; it always drives the fixed port set
//! `(clk, pb[3:0], dipsw[4:0], led[4:0])`. This wrapper absorbs all
//! per-project variance: it instantiates the user top module and wires its
//! ports to the board signals from the resolved mapping.
//!
//! Tie rules: an unmapped board LED reads `1'b1` (off, the LED is active
//! low). An extra user input is tied to `1'b1`, which matches the board's
//! weak pull-up rule for unused pins. An extra user output dangles.

use crate::mapping::{BoardMapping, PortBit};
use crate::ports::{PortDir, TopPorts};

/// Render the wrapper source text.
pub fn generate_wrapper(mapping: &BoardMapping, ports: &TopPorts) -> String {
    let mut s = String::new();
    s.push_str("// Generated by jade for the board simulation. Do not edit.\n");
    s.push_str("/* verilator lint_off UNUSEDSIGNAL */\n");
    s.push_str("/* verilator lint_off PINCONNECTEMPTY */\n");
    s.push_str("module jade_hw_top (\n");
    s.push_str("    input  wire       clk,\n");
    s.push_str("    input  wire [3:0] pb,\n");
    s.push_str("    input  wire [4:0] dipsw,\n");
    s.push_str("    output wire [4:0] led\n");
    s.push_str(");\n");

    // One wire per user output port, with the declared range.
    for port in &ports.ports {
        if port.dir != PortDir::Output {
            continue;
        }
        if port.has_range {
            s.push_str(&format!(
                "    wire [{}:{}] uo_{};\n",
                port.msb, port.lsb, port.name
            ));
        } else {
            s.push_str(&format!("    wire uo_{};\n", port.name));
        }
    }

    // The user instance with named connections.
    s.push_str(&format!("    {} u_top (\n", mapping.top));
    let mut conns: Vec<String> = Vec::new();
    for port in &ports.ports {
        match port.dir {
            PortDir::Input => {
                conns.push(format!(
                    "        .{}({})",
                    port.name,
                    input_expr(mapping, port.name.as_str(), port.msb, port.lsb, port.has_range)
                ));
            }
            PortDir::Output => {
                conns.push(format!("        .{}(uo_{})", port.name, port.name));
            }
            PortDir::Inout => {
                // The board table has no bidirectional signals; dangle.
                conns.push(format!("        .{}()", port.name));
            }
        }
    }
    s.push_str(&conns.join(",\n"));
    s.push_str("\n    );\n");

    // Board LEDs read the mapped output bits; unmapped LEDs stay off.
    for i in 0..5 {
        let expr = match &mapping.leds[i] {
            Some(pb) => bit_ref("uo_", pb),
            None => "1'b1".to_string(),
        };
        s.push_str(&format!("    assign led[{i}] = {expr};\n"));
    }

    s.push_str("endmodule\n");
    s
}

/// Reference one bit of a user port, with the `uo_` prefix for outputs.
fn bit_ref(prefix: &str, pb: &PortBit) -> String {
    if pb.scalar {
        format!("{prefix}{}", pb.port)
    } else {
        format!("{prefix}{}[{}]", pb.port, pb.bit)
    }
}

/// Build the expression for one user input port: the board signal per bit,
/// MSB first, `1'b1` for unmapped bits.
fn input_expr(mapping: &BoardMapping, port: &str, msb: u32, lsb: u32, has_range: bool) -> String {
    let bit_value = |bit: u32| -> String {
        let hit = |slot: &Option<PortBit>| -> bool {
            slot.as_ref().is_some_and(|pb| pb.port == port && pb.bit == bit)
        };
        if hit(&mapping.clk) {
            return "clk".to_string();
        }
        for (i, slot) in mapping.pbs.iter().enumerate() {
            if hit(slot) {
                return format!("pb[{i}]");
            }
        }
        for (i, slot) in mapping.dips.iter().enumerate() {
            if hit(slot) {
                return format!("dipsw[{i}]");
            }
        }
        "1'b1".to_string()
    };
    if !has_range {
        return bit_value(lsb);
    }
    if msb == lsb {
        return format!("{{{}}}", bit_value(lsb));
    }
    let parts: Vec<String> = (lsb..=msb).rev().map(bit_value).collect();
    format!("{{{}}}", parts.join(", "))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::board::dk_dev_10m50a;
    use crate::mapping::resolve;
    use crate::ports::{Port, TopPorts};
    use crate::qsf::parse_qsf;
    use std::path::Path;

    #[test]
    fn blink_wrapper_snapshot() {
        let ports = TopPorts {
            module: "blink".into(),
            ports: vec![
                Port { name: "clk".into(), dir: PortDir::Input, msb: 0, lsb: 0, has_range: false },
                Port { name: "button".into(), dir: PortDir::Input, msb: 0, lsb: 0, has_range: false },
                Port { name: "led".into(), dir: PortDir::Output, msb: 4, lsb: 0, has_range: true },
            ],
        };
        let text = "\
set_global_assignment -name TOP_LEVEL_ENTITY blink
set_location_assignment PIN_M9 -to clk
set_location_assignment PIN_T20 -to led[0]
set_location_assignment PIN_U22 -to led[1]
set_location_assignment PIN_U21 -to led[2]
set_location_assignment PIN_AA21 -to led[3]
set_location_assignment PIN_AA22 -to led[4]
set_location_assignment PIN_L22 -to button
";
        let qsf = parse_qsf(Path::new("blink.qsf"), text);
        let m = resolve(Some(&qsf), &ports, &dk_dev_10m50a()).unwrap();
        let v = generate_wrapper(&m, &ports);
        let expected = "\
// Generated by jade for the board simulation. Do not edit.
/* verilator lint_off UNUSEDSIGNAL */
/* verilator lint_off PINCONNECTEMPTY */
module jade_hw_top (
    input  wire       clk,
    input  wire [3:0] pb,
    input  wire [4:0] dipsw,
    output wire [4:0] led
);
    wire [4:0] uo_led;
    blink u_top (
        .clk(clk),
        .button(pb[0]),
        .led(uo_led)
    );
    assign led[0] = uo_led[0];
    assign led[1] = uo_led[1];
    assign led[2] = uo_led[2];
    assign led[3] = uo_led[3];
    assign led[4] = uo_led[4];
endmodule
";
        assert_eq!(v, expected);
    }

    #[test]
    fn unmapped_leds_tie_high_and_extra_inputs_tie_high() {
        // A design with led[1:0] and an extra enable input, no qsf.
        let ports = TopPorts {
            module: "top".into(),
            ports: vec![
                Port { name: "clk".into(), dir: PortDir::Input, msb: 0, lsb: 0, has_range: false },
                Port { name: "enable".into(), dir: PortDir::Input, msb: 1, lsb: 0, has_range: true },
                Port { name: "led".into(), dir: PortDir::Output, msb: 1, lsb: 0, has_range: true },
            ],
        };
        let m = resolve(None, &ports, &dk_dev_10m50a()).unwrap();
        let v = generate_wrapper(&m, &ports);
        assert!(v.contains(".enable({1'b1, 1'b1})"));
        assert!(v.contains("assign led[2] = 1'b1;"));
        assert!(v.contains("assign led[4] = 1'b1;"));
        assert!(v.contains("assign led[0] = uo_led[0];"));
    }
}
